In [1]:
import pandas as pd
df= pd.read_csv('Data/shopping_trends.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:

from geopy.geocoders import Nominatim

def get_coordinates(state_name):
    geolocator = Nominatim(user_agent="shopping_trends")  
    location = geolocator.geocode(state_name, language='en')
    if location:
        return location.latitude, location.longitude
    else:
        return None

df= pd.read_csv('Data/shopping_trends.csv')
state_column = 'Location'

df['Latitude'] = None
df['Longitude'] = None

for index, row in df.iterrows():
    state_name = row[state_column]
    coordinates = get_coordinates(state_name)
    if coordinates:
        df.at[index, 'Latitude'] = coordinates[0]
        df.at[index, 'Longitude'] = coordinates[1]
df.to_csv('Data/shopping_trends_geo.csv', index=False)

print(f"Latitude and Longitude added and DataFrame saved ")

Latitude and Longitude added and DataFrame saved

In [5]:
df2= pd.read_csv('Data/shopping_trends_geo.csv')
df2.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases,Latitude,Longitude
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,37.572603,-85.155141
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,45.709097,-68.859020
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,42.378877,-72.032366
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,41.796241,-71.599237
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,43.979280,-120.737257